services:
  prometheus:
    image: prom/prometheus:v3.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/:z
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-otlp-receiver
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo:2.7.2
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config-tempo.yaml:/etc/tempo.yaml:z
    ports:
      - "3200:3200"
      - "5001:5001"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.0.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:z
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:z
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/trustify.json
      - GF_EXPLORE_ENABLED=false
      - GF_HELP_ENABLED=false
      - GF_LOG_LEVEL=error
      - GF_NEWS_ENABLED=false
      - GF_NEWS_NEWS_FEED_ENABLED=false
      - GF_PROFILE_ENABLED=false
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_DEFAULT_THEME=light
    restart: unless-stopped

  collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.127.0
    command: ["--config=/otel-collector-config.yaml"]
    volumes:
      - './config-collector.yaml:/otel-collector-config.yaml:z'
    ports:
      - "4317:4317"
      - "8888:8888"
    depends_on: [tempo]
