services:
  prometheus:
    image: prom/prometheus:v3.1.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-otlp-receiver
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo:2.7.2
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config-tempo.yaml:/etc/tempo.yaml:z
    ports:
      - "3200:3200"
      - "5001:5001"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.0.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:z
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:z
      - ./grafana/dashboards/traces.json:/var/lib/grafana/dashboards/traces.json:z
      - ./grafana/dashboards/metrics.json:/var/lib/grafana/dashboards/metrics.json:z
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_LOG_LEVEL=error
    restart: unless-stopped

  collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.127.0
    command: ["--config=/otel-collector-config.yaml"]
    volumes:
      - './config-collector.yaml:/otel-collector-config.yaml:z'
    ports:
      - "4317:4317"
      - "8888:8888"
    depends_on: [tempo]
