server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:5001"
        http:

compactor:
  compaction:
    block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces

overrides:
  metrics_generator_processors: ['local-blocks']

metrics_generator:
  storage:
    path: /var/tempo/generator
  traces_storage:
    path: /var/tempo/generator/traces
  processor:
    span_metrics:
    service_graphs:
    local_blocks:
      flush_to_storage: true
      filter_server_spans: false
