[package]
name = "trustify-module-storage"
version = "0.1.0-alpha.4"
edition = "2021"
publish = false

[dependencies]
trustify-common = { workspace = true }

actix-web = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["full"] }
utoipa = { workspace = true, features = ["actix_extras"] }

[dev-dependencies]
serde_json = { workspace = true }
test-log = { workspace = true, features = ["log", "trace"] }
test-context = { workspace = true }
