ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - frontend/**

backend:
  - changed-files:
      - any-glob-to-any-file:
          - backend/**
