[package]
name = "trustify-cvss"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
test-log = { workspace = true, features = ["env_logger", "trace"] }
tokio = { workspace = true, features = ["full"] }
