[package]
name = "trustify-module-ui"
version = "0.1.0-alpha.11"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
actix-web-static-files = { workspace = true }
anyhow = { workspace = true }
trustify-ui = { workspace = true }

