[workspace]
resolver = "2"
members = [
  "common",
  "common/auth",
  "common/infrastructure",
  "cvss",
  "entity",
  "integration-tests",
  "migration",
  "modules/importer",
  "modules/ui",
  "modules/fundamental",
  "modules/ingestor",
  "modules/storage",
  "modules/graphql",
  "server",
  "trustd",
]

[workspace.dependencies]
actix = "0.13.3"
actix-cors = "0.7"
actix-http = "3.3.1"
actix-tls = "3"
actix-web = "4.3.1"
actix-web-extras = "0.1"
actix-web-httpauth = "0.8"
actix-web-opentelemetry = "0.17"
actix-web-prom = "0.8.0"
actix-web-static-files = "4.0.1"
anyhow = "1.0.72"
async-graphql = "7.0.5"
async-graphql-actix-web = "7.0.5"
async-std = "1"
async-trait = "0.1.74"
base64 = "0.22"
biscuit = "0.7"
bytes = "1.5"
bytesize = "1.3"
chrono = { version = "0.4.35", default-features = false }
clap = "4"
concat-idents = "1"
cpe = "0.1.3"
csaf = { version = "0.5.0", default-features = false }
csaf-walker = { version = "0.8.0", default-features = false }
cve = "0.3.1"
cyclonedx-bom = "0.6.1"
env_logger = "0.11.0"
futures = "0.3.30"
futures-util = "0.3"
garage-door = "0.1.0"
git2 = { version = "0.19.0", features = ["ssh"] }
hex = "0.4.3"
hide = "0.1.5"
http = "1"
human-date-parser = "0.1"
humantime = "2"
humantime-serde = "1"
indicatif = "0.17.8"
indicatif-log-bridge = "0.2"
itertools = "0.13"
jsn = "0.14"
jsonpath-rust = "0.6.1"
lenient_semver = "0.4.2"
libz-sys = "*"
log = "0.4.19"
native-tls = "0.2"
once_cell = "1.19.0"
openid = "0.14"
openssl = "0.10"
opentelemetry = "0.22"
opentelemetry-otlp = "0.15"
opentelemetry_sdk = "0.22"
osv = { version = "0.2.0", default-features = false }
packageurl = "0.3.0"
parking_lot = "0.12"
pem = "3"
postgresql_archive = "0.14.0"
postgresql_embedded = "0.14.0"
prometheus = "0.13.3"
rand = "0.8.5"                                                        # for testing
regex = "1.10.3"
reqwest = "0.12"
ring = "0.17.8"
rstest = "0.21"
rust-lzma = "0.6.0"
sbom-walker = { version = "0.8.0", default-features = false }
schemars = "0.8"
sea-orm = "0.12"
sea-orm-migration = "0.12.2"
sea-query = "0.30.0"
serde = "1.0.183"
serde_json = "1.0.114"
serde_yaml = "=0.8.26"
sha2 = "0.10.8"
spdx-expression = "0.5.2"
spdx-rs = "0.5.3"
sqlx = "0.7"
static-files = "0.2.3"
temp-env = "0.3"
tempfile = "3"
test-context = "0.3"
test-log = "0.2.16"
thiserror = "1.0.58"
time = "0.3"
tokio = "1.30.0"
tokio-util = "0.7"
tracing = "0.1"
tracing-bunyan-formatter = "0.3.7"
tracing-opentelemetry = "0.23"
tracing-subscriber = { version = "0.3.17", default-features = false }
url = "2.5.0"
urlencoding = "2"
utoipa = "4"
utoipa-swagger-ui = "7.1.0"
uuid = "1.7.0"
walkdir = "2.5"
walker-common = "0.8.0"
walker-extras = "0.8.0"

trustify-auth = { path = "common/auth", features = ["actix", "swagger"] }
trustify-common = { path = "common" }
trustify-cvss = { path = "cvss" }
trustify-entity = { path = "entity" }
trustify-infrastructure = { path = "common/infrastructure" }
trustify-migration = { path = "migration" }
trustify-module-fundamental = { path = "modules/fundamental" }
trustify-module-importer = { path = "modules/importer" }
trustify-module-ui = { path = "modules/ui", default-features = false }
trustify-server = { path = "server", default-features = false }
trustify-ui = { git = "https://github.com/trustification/trustify-ui.git", tag = "static-main" }
trustify-module-ingestor = { path = "modules/ingestor" }
trustify-module-storage = { path = "modules/storage" }
trustify-module-graphql = { path = "modules/graphql" }

[patch.crates-io]
#csaf-walker = { git = "https://github.com/ctron/csaf-walker", rev = "7b6e64dd56e4be79e184b053ef754a42e1496fe0" }
#sbom-walker = { git = "https://github.com/ctron/csaf-walker", rev = "7b6e64dd56e4be79e184b053ef754a42e1496fe0" }
#walker-common = { git = "https://github.com/ctron/csaf-walker", rev = "7b6e64dd56e4be79e184b053ef754a42e1496fe0" }
#walker-extras = { git = "https://github.com/ctron/csaf-walker", rev = "7b6e64dd56e4be79e184b053ef754a42e1496fe0" }

#csaf-walker = { path = "../csaf-walker/csaf" }
#sbom-walker = { path = "../csaf-walker/sbom" }
#walker-common = { path = "../csaf-walker/common" }
#walker-extras = { path = "../csaf-walker/extras" }

#garage-door = { git = "https://github.com/ctron/garage-door", rev = "c02fdbbb95d4482d97497dfb62c41dede023b2ea" }
#garage-door = { path = "../garage-door" }
#oxide-auth = { git = "https://github.com/ctron/oxide-auth", rev = "cd0c79c48a702ea6bb0b05e95e9eddcba8f6c77f" }

# required due to https://github.com/KenDJohnson/cpe-rs/pull/15
cpe = { git = "https://github.com/ctron/cpe-rs", rev = "c3c05e637f6eff7dd4933c2f56d070ee2ddfb44b" }
