[package]
name = "trustify-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
tera = "1.19.1"
base64 = { workspace = true }