[package]
name = "trustify-query-derive"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
