[package]
name = "xtask"
version = "0.1.0-alpha.11"
edition = "2021"
publish = false

[dependencies]
trustify-server = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
