[package]
name = "trustify-module-vulnerability"
version = "0.1.0"
edition = "2021"

[dependencies]
trustify-entity = { workspace = true }
trustify-common = { workspace = true }
trustify-model = { workspace = true }

actix-web = { workspace = true }
anyhow = { workspace = true }
sea-orm = { workspace = true, features = ["sea-query-binder", "sqlx-postgres", "runtime-tokio-rustls", "macros", "debug-print"] }
thiserror = { workspace = true }
utoipa = { workspace = true, features = ["actix_extras"] }

[dev-dependencies]
trustify-cvss = { workspace = true }
time = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
chrono = { workspace = true }
humantime = { workspace = true }
jsonpath-rust = { workspace = true }
rust-lzma = { workspace = true }
test-log = { workspace = true, features = ["log", "trace"] }
trustify-module-ingestor = { workspace = true }
trustify-module-storage = { workspace = true }
test-context = { workspace = true }
urlencoding = { workspace = true }
tokio-util = { workspace = true }
actix-http = { workspace = true }
