[package]
name = "trustify-entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "0.12", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-json" ] }
serde_json = "1"
tokio = { version = "1.30.0", features = ["full"] }

[dev-dependencies]
anyhow = "1.0.72"
