[package]
name = "trustify-entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { workspace = true, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-json"] }
serde_json = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["full"] }
trustify-common = { path = "../common" }
trustify-cvss = { path = "../cvss" }
chrono = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
