[package]
name = "trustify-module-organization"
version = "0.1.0"
edition = "2021"

[dependencies]
trustify-entity = { workspace = true }
trustify-common = { workspace = true }
trustify-model = { workspace = true }

actix-web = { workspace = true }
anyhow = { workspace = true }
sea-orm = { workspace = true, features = ["sea-query-binder", "sqlx-postgres", "runtime-tokio-rustls", "macros", "debug-print"] }

utoipa = { workspace = true, features = ["actix_extras"] }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
test-log = { workspace = true, features = ["log", "trace"] }
test-context = { workspace = true }
trustify-module-ingestor = { workspace = true }
trustify-module-storage = { workspace = true }
jsonpath-rust = { workspace = true }