[package]
name = "trustify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
trustify-auth = { workspace = true }
trustify-common = { workspace = true }
trustify-infrastructure = { workspace = true }
trustify-module-importer = { workspace = true }
trustify-module-ui = { workspace = true }
trustify-module-fundamental = { workspace = true }
trustify-module-ingestor = { workspace = true }
trustify-module-storage = { workspace = true }
actix-web = { workspace = true }
anyhow = { workspace = true }
bytesize = { workspace = true }
clap = { workspace = true, features = ["derive"] }
futures = { workspace = true }
log = { workspace = true }
url = "2"
utoipa = { workspace = true, features = ["actix_extras"] }
utoipa-swagger-ui = { workspace = true, features = ["actix-web"] }

[dev-dependencies]
urlencoding = { workspace = true }

[features]
default = [ "ui" ]
ui = ["trustify-module-ui/ui"]
