[package]
name = "trustify-common"
version = "0.1.0"
edition = "2021"

[dependencies]
trustify-migration = { path = "../migration" }
trustify-cvss = { path = "../cvss" }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
cpe = { workspace = true }
lenient_semver = { workspace = true }
log = { workspace = true }
native-tls = { workspace = true }
packageurl = { workspace = true }
pem = { workspace = true }
postgresql_embedded = { workspace = true, features = ["blocking", "bundled", "tokio"] }
reqwest = { workspace = true, features = ["native-tls"] }
utoipa = { workspace = true }
sea-orm = { workspace = true, features = ["sea-query-binder", "sqlx-postgres", "runtime-tokio-rustls", "macros"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
test-log = { workspace = true, features = ["env_logger", "trace"] }
tokio = { workspace = true, features = ["full"] }
