use crate::error::ErrorInformation;
use std::{
    collections::{HashMap, HashSet},
    marker::PhantomData,
};

macro_rules! capability {
    (
        $(#[$enum_meta:meta])*
        $vis:vis enum $name:ident {
            $(
                $(#[$variant_meta:meta])*
                $variant:ident
            ),* $(,)?
        }
    ) => {
        $(#[$enum_meta])*
        $vis enum $name {
            $(
                $(#[$variant_meta])*
                $variant,
            )*
        }

        $(
            /// Marker type for the capability gate.
            pub struct $variant;

            impl CapabilityRequirement for $variant {
                fn capability() -> Capability {
                    Capability::$variant
                }
            }
        )*
    };
}

capability! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, strum::Display)]
    #[serde(rename_all = "camelCase")]
    pub enum Capability {
        #[strum(serialize = "exploitIntelligence")]
        ExploitIntelligence,
        #[strum(serialize = "recommendations")]
        Recommendations,
        #[strum(serialize = "semanticValidation")]
        SemanticValidation,
    }
}

/// The set of capabilities that are active on this instance.
///
/// Built once at startup and registered as `web::Data<ActiveCapabilities>`.
#[derive(Clone, Debug, Default)]
pub struct ActiveCapabilities(HashSet<Capability>);

impl ActiveCapabilities {
    /// Returns `Ok(())` if the capability is active, or `Err(CapabilityDisabled)` if not.
    pub fn require(&self, capability: Capability) -> Result<(), CapabilityDisabled> {
        if self.0.contains(&capability) {
            Ok(())
        } else {
            Err(CapabilityDisabled(capability))
        }
    }

    /// Check whether a capability is active.
    pub fn contains(&self, capability: &Capability) -> bool {
        self.0.contains(capability)
    }

    /// Add a capability to the active set.
    pub fn insert(&mut self, capability: Capability) {
        self.0.insert(capability);
    }

    /// Return the active capability names as a sorted vector (for the well-known response).
    pub fn as_sorted_vec(&self) -> Vec<String> {
        let mut v: Vec<_> = self.0.iter().map(|f| f.to_string()).collect();
        v.sort();
        v
    }
}

impl FromIterator<Capability> for ActiveCapabilities {
    fn from_iter<I: IntoIterator<Item = Capability>>(iter: I) -> Self {
        Self(iter.into_iter().collect())
    }
}

/// Trait implemented by capability marker types (generated by the `capability!` macro).
pub trait CapabilityRequirement {
    /// The capability this marker represents.
    fn capability() -> Capability;
}

/// Error returned when a capability check fails.
#[derive(Debug, thiserror::Error)]
#[error("The '{0}' capability is not configured on this instance.")]
pub struct CapabilityDisabled(pub Capability);

impl actix_web::ResponseError for CapabilityDisabled {
    fn status_code(&self) -> actix_web::http::StatusCode {
        actix_web::http::StatusCode::UNPROCESSABLE_ENTITY
    }

    fn error_response(&self) -> actix_web::HttpResponse {
        actix_web::HttpResponse::UnprocessableEntity().json(ErrorInformation {
            error: "CapabilityDisabled".into(),
            message: self.to_string(),
            details: None,
        })
    }
}

/// Active variants by category.
///
/// Each entry maps a category name (e.g., `"importers"`) to the list of
/// active variants within that category. Registered as `web::Data<Variants>`.
pub type Variants = HashMap<String, Vec<String>>;

/// A variant was checked but is not enabled on this instance.
#[derive(Debug, thiserror::Error)]
#[error("{kind} '{name}' is disabled on this instance")]
pub struct VariantDisabled {
    pub kind: String,
    pub name: String,
}

impl actix_web::ResponseError for VariantDisabled {
    fn status_code(&self) -> actix_web::http::StatusCode {
        actix_web::http::StatusCode::UNPROCESSABLE_ENTITY
    }

    fn error_response(&self) -> actix_web::HttpResponse {
        actix_web::HttpResponse::UnprocessableEntity().json(ErrorInformation {
            error: "VariantDisabled".into(),
            message: self.to_string(),
            details: None,
        })
    }
}

/// A resolved set of enabled variant names within a category.
///
/// Built once at startup from `--enable-*` / `--disable-*` CLI args.
/// `None` in the inner set means "allow all" (the default).
#[derive(Clone, Debug, Default)]
pub struct VariantFilter {
    kind: String,
    enabled: Option<HashSet<String>>,
}

impl VariantFilter {
    /// Resolve enable/disable lists against a full set of valid names.
    ///
    /// - Both empty → all enabled (default)
    /// - `enable` non-empty → only those enabled (`*` expands to all)
    /// - `disable` non-empty → all minus those (`*` expands to all)
    ///
    /// Caller guarantees `enable` and `disable` are mutually exclusive
    /// (enforced by clap `conflicts_with`).
    pub fn new(
        kind: impl Into<String>,
        all: &[&str],
        enable: &[String],
        disable: &[String],
    ) -> Self {
        let kind = kind.into();
        if !enable.is_empty() {
            let enabled = if enable.iter().any(|s| s == "*") {
                all.iter().map(|s| (*s).to_string()).collect()
            } else {
                enable.iter().cloned().collect()
            };
            Self {
                kind,
                enabled: Some(enabled),
            }
        } else if !disable.is_empty() {
            let disabled: HashSet<&str> = if disable.iter().any(|s| s == "*") {
                all.iter().copied().collect()
            } else {
                disable.iter().map(|s| s.as_str()).collect()
            };
            let enabled = all
                .iter()
                .filter(|name| !disabled.contains(*name))
                .map(|s| (*s).to_string())
                .collect();
            Self {
                kind,
                enabled: Some(enabled),
            }
        } else {
            Self {
                kind,
                enabled: None,
            }
        }
    }

    /// Check whether a name is enabled, returning an error if not.
    pub fn try_enabled(&self, name: &str) -> Result<(), VariantDisabled> {
        match &self.enabled {
            None => Ok(()),
            Some(set) if set.contains(name) => Ok(()),
            _ => Err(VariantDisabled {
                kind: self.kind.clone(),
                name: name.to_string(),
            }),
        }
    }

    /// Return the enabled names as a sorted vector.
    ///
    /// When no filter is configured, `all` is used as the full set.
    pub fn as_sorted_vec(&self, all: &[&str]) -> Vec<String> {
        let mut v: Vec<_> = match &self.enabled {
            None => all.iter().map(|s| (*s).to_string()).collect(),
            Some(set) => set.iter().cloned().collect(),
        };
        v.sort();
        v
    }
}

/// Actix-web extractor that rejects requests when a capability is not active.
///
/// Add `_gate: RequireCapability<MyCapability>` to a handler signature to gate
/// the entire endpoint on that capability.
pub struct RequireCapability<T: CapabilityRequirement>(PhantomData<T>);

impl<T: CapabilityRequirement> actix_web::FromRequest for RequireCapability<T> {
    type Error = CapabilityDisabled;
    type Future = core::future::Ready<Result<Self, Self::Error>>;

    fn from_request(
        req: &actix_web::HttpRequest,
        _payload: &mut actix_web::dev::Payload,
    ) -> Self::Future {
        fn enforce<T: CapabilityRequirement>(
            req: &actix_web::HttpRequest,
        ) -> Result<RequireCapability<T>, CapabilityDisabled> {
            let capabilities = req
                .app_data::<actix_web::web::Data<ActiveCapabilities>>()
                .map(|d| d.get_ref())
                .cloned()
                .unwrap_or_default();

            capabilities.require(T::capability())?;

            Ok(RequireCapability(PhantomData))
        }

        core::future::ready(enforce::<T>(req))
    }
}
