use crate::error::ErrorInformation;
use std::{
    collections::{HashMap, HashSet},
    marker::PhantomData,
};

macro_rules! feature {
    (
        $(#[$enum_meta:meta])*
        $vis:vis enum $name:ident {
            $(
                $(#[$variant_meta:meta])*
                $variant:ident
            ),* $(,)?
        }
    ) => {
        $(#[$enum_meta])*
        $vis enum $name {
            $(
                $(#[$variant_meta])*
                $variant,
            )*
        }

        $(
            /// Marker type for the feature gate.
            pub struct $variant;

            impl FeatureRequirement for $variant {
                fn feature() -> Feature {
                    Feature::$variant
                }
            }
        )*
    };
}

feature! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, strum::Display)]
    #[serde(rename_all = "camelCase")]
    pub enum Feature {
        #[strum(serialize = "exploitIntelligence")]
        ExploitIntelligence,
        #[strum(serialize = "recommendations")]
        Recommendations,
        #[strum(serialize = "semanticValidation")]
        SemanticValidation,
    }
}

/// The set of features that are active on this instance.
///
/// Built once at startup and registered as `web::Data<ActiveFeatures>`.
#[derive(Clone, Debug, Default)]
pub struct ActiveFeatures(HashSet<Feature>);

impl ActiveFeatures {
    /// Returns `Ok(())` if the feature is active, or `Err(FeatureDisabled)` if not.
    pub fn require(&self, feature: Feature) -> Result<(), FeatureDisabled> {
        if self.0.contains(&feature) {
            Ok(())
        } else {
            Err(FeatureDisabled(feature))
        }
    }

    /// Check whether a feature is active.
    pub fn contains(&self, feature: &Feature) -> bool {
        self.0.contains(feature)
    }

    /// Add a feature to the active set.
    pub fn insert(&mut self, feature: Feature) {
        self.0.insert(feature);
    }

    /// Return the active feature names as a sorted vector (for the well-known response).
    pub fn as_sorted_vec(&self) -> Vec<String> {
        let mut v: Vec<_> = self.0.iter().map(|f| f.to_string()).collect();
        v.sort();
        v
    }
}

impl FromIterator<Feature> for ActiveFeatures {
    fn from_iter<I: IntoIterator<Item = Feature>>(iter: I) -> Self {
        Self(iter.into_iter().collect())
    }
}

/// Trait implemented by feature marker types (generated by the `feature!` macro).
pub trait FeatureRequirement {
    /// The feature variant this marker represents.
    fn feature() -> Feature;
}

/// Error returned when a feature gate check fails.
#[derive(Debug, thiserror::Error)]
#[error("The '{0}' feature is not configured on this instance.")]
pub struct FeatureDisabled(pub Feature);

impl actix_web::ResponseError for FeatureDisabled {
    fn status_code(&self) -> actix_web::http::StatusCode {
        actix_web::http::StatusCode::SERVICE_UNAVAILABLE
    }

    fn error_response(&self) -> actix_web::HttpResponse {
        actix_web::HttpResponse::ServiceUnavailable().json(ErrorInformation {
            error: "FeatureDisabled".into(),
            message: self.to_string(),
            details: None,
        })
    }
}

/// Active capabilities by category.
///
/// Each entry maps a category name (e.g., `"importers"`) to the list of
/// active options within that category. Registered as `web::Data<Capabilities>`.
pub type Capabilities = HashMap<String, Vec<String>>;

/// A capability was checked but is not enabled on this instance.
#[derive(Debug, thiserror::Error)]
#[error("{kind} '{name}' is disabled on this instance")]
pub struct CapabilityDisabled {
    pub kind: String,
    pub name: String,
}

impl actix_web::ResponseError for CapabilityDisabled {
    fn status_code(&self) -> actix_web::http::StatusCode {
        actix_web::http::StatusCode::UNPROCESSABLE_ENTITY
    }

    fn error_response(&self) -> actix_web::HttpResponse {
        actix_web::HttpResponse::UnprocessableEntity().json(ErrorInformation {
            error: "CapabilityDisabled".into(),
            message: self.to_string(),
            details: None,
        })
    }
}

/// A resolved set of enabled variant names within a capability category.
///
/// Built once at startup from `--enable-*` / `--disable-*` CLI args.
/// `None` in the inner set means "allow all" (the default).
#[derive(Clone, Debug, Default)]
pub struct CapabilityFilter {
    kind: String,
    enabled: Option<HashSet<String>>,
}

impl CapabilityFilter {
    /// Resolve enable/disable lists against a full set of valid names.
    ///
    /// - Both empty → all enabled (default)
    /// - `enable` non-empty → only those enabled (`*` expands to all)
    /// - `disable` non-empty → all minus those (`*` expands to all)
    ///
    /// Caller guarantees `enable` and `disable` are mutually exclusive
    /// (enforced by clap `conflicts_with`).
    pub fn new(
        kind: impl Into<String>,
        all: &[&str],
        enable: &[String],
        disable: &[String],
    ) -> Self {
        let kind = kind.into();
        if !enable.is_empty() {
            let enabled = if enable.iter().any(|s| s == "*") {
                all.iter().map(|s| (*s).to_string()).collect()
            } else {
                enable.iter().cloned().collect()
            };
            Self {
                kind,
                enabled: Some(enabled),
            }
        } else if !disable.is_empty() {
            let disabled: HashSet<&str> = if disable.iter().any(|s| s == "*") {
                all.iter().copied().collect()
            } else {
                disable.iter().map(|s| s.as_str()).collect()
            };
            let enabled = all
                .iter()
                .filter(|name| !disabled.contains(*name))
                .map(|s| (*s).to_string())
                .collect();
            Self {
                kind,
                enabled: Some(enabled),
            }
        } else {
            Self {
                kind,
                enabled: None,
            }
        }
    }

    /// Check whether a name is enabled, returning an error if not.
    pub fn try_enabled(&self, name: &str) -> Result<(), CapabilityDisabled> {
        match &self.enabled {
            None => Ok(()),
            Some(set) if set.contains(name) => Ok(()),
            _ => Err(CapabilityDisabled {
                kind: self.kind.clone(),
                name: name.to_string(),
            }),
        }
    }

    /// Return the enabled names as a sorted vector.
    ///
    /// When no filter is configured, `all` is used as the full set.
    pub fn as_sorted_vec(&self, all: &[&str]) -> Vec<String> {
        let mut v: Vec<_> = match &self.enabled {
            None => all.iter().map(|s| (*s).to_string()).collect(),
            Some(set) => set.iter().cloned().collect(),
        };
        v.sort();
        v
    }
}

/// Actix-web extractor that rejects requests when a feature is not active.
///
/// Add `_gate: RequireFeature<MyFeature>` to a handler signature to gate
/// the entire endpoint on that feature.
pub struct RequireFeature<T: FeatureRequirement>(PhantomData<T>);

impl<T: FeatureRequirement> actix_web::FromRequest for RequireFeature<T> {
    type Error = FeatureDisabled;
    type Future = core::future::Ready<Result<Self, Self::Error>>;

    fn from_request(
        req: &actix_web::HttpRequest,
        _payload: &mut actix_web::dev::Payload,
    ) -> Self::Future {
        fn enforce<T: FeatureRequirement>(
            req: &actix_web::HttpRequest,
        ) -> Result<RequireFeature<T>, FeatureDisabled> {
            let features = req
                .app_data::<actix_web::web::Data<ActiveFeatures>>()
                .map(|d| d.get_ref())
                .cloned()
                .unwrap_or_default();

            features.require(T::feature())?;

            Ok(RequireFeature(PhantomData))
        }

        core::future::ready(enforce::<T>(req))
    }
}
