[package]
name = "trustify-trustd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "trustd"
path = "src/main.rs"

[dependencies]
trustify-server = { workspace = true }
trustify-importer = { workspace = true }
trustify-common = { workspace = true }
trustify-infrastructure = { workspace = true }
trustify-auth = { workspace = true }
actix-web = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
log = { workspace = true }
postgresql_embedded = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
