[package]
name = "trustify-trustd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "trustd"
path = "src/main.rs"

[dependencies]
trustify-server = { path = "../server"}
trustify-importer = { path = "../importer"}
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
log = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
