[package]
name = "trustify-scanner"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "trustify-scanner"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
comfy-table = "7"
flate2 = { workspace = true }
oci-client = { workspace = true }
reqwest = { workspace = true, features = ["json", "gzip", "form"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "ansi"] }
url = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
