[package]
name = "trustify-module-ingestor"
version = "0.1.0-alpha.1"
edition = "2021"
publish = false

[dependencies]
trustify-common = { workspace = true }
trustify-cvss = { workspace = true }
trustify-entity = { workspace = true }
trustify-module-storage = { workspace = true }

actix-web = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
bytesize = { workspace = true }
cpe = { workspace = true }
csaf = { workspace = true }
cyclonedx-bom = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
humantime = { workspace = true }
lenient_semver = { workspace = true }
log = { workspace = true }
packageurl = { workspace = true }
ring = { workspace = true }
sea-orm = { workspace = true }
sea-query = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
spdx-expression = { workspace = true }
spdx-rs = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["serde-well-known"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true, features = ["actix_extras"] }
uuid = { workspace = true, features = ["v7"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
rand = { workspace = true }
rust-lzma = { workspace = true }
test-context = { workspace = true }
test-log = { workspace = true, features = ["log", "trace"] }
