[package]
name = "trustify-module-ingestor"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
actix-web = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
cpe = { workspace = true }
csaf = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
humantime = { workspace = true }
lenient_semver = { workspace = true }
log = { workspace = true }
packageurl = { workspace = true }
postgresql_embedded = { workspace = true, features = ["blocking", "bundled", "tokio"] }
reqwest = { workspace = true }
ring = { workspace = true }
sbom-walker = { workspace = true, features = ["crypto-openssl", "cyclonedx-bom", "spdx-rs"] }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
sea-query = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["serde-well-known"] }
tokio = { workspace = true, features = ["full"] }
spdx-expression = { workspace = true }
spdx-rs = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
trustify-common = { workspace = true }
trustify-cvss = { workspace = true }
trustify-entity = { workspace = true }
trustify-migration = { workspace = true }
trustify-module-storage = { workspace = true }
trustify-module-search = { workspace = true }
utoipa = { workspace = true, features = ["actix_extras"] }

[dev-dependencies]
test-log = { workspace = true, features = ["env_logger", "trace"] }
rust-lzma = "0.6"
url-escape = { workspace = true }
rand = { workspace = true }
test-context = { workspace = true }