[package]
name = "trustify-module-correlation"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
lzma-rs = "0.3"
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
vers-rs = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
test-log = { workspace = true, features = ["log", "trace"] }
