name: backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**"
      - ".github/workflows/**"

env:
  CARGO_TERM_COLOR: always

jobs:

  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: .

    - name: Install nettle
      run: |
        sudo apt-get update
        sudo apt install clang llvm pkg-config nettle-dev

    - name: Format
      run: cargo fmt --check
    - name: Check
      run: cargo check
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::unwrap_used
    - name: Test
      run: cargo test -- --nocapture
      env:
        RUST_LOG: debug
