name: backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3
    - name: Format
      run: cargo fmt --check
    - name: Check
      run: cargo check
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::unwrap_used

    # - name: Test (requires postgresql)
    #   run: cargo test
