name: backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:

  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    services:
      postgres:
        image: docker.io/library/postgres:16
        env:
          POSTGRES_PASSWORD: eggs
          POSTGRES_DB: huevos
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: backend

    - name: Install nettle
      run: |
        sudo apt-get update
        sudo apt install clang llvm pkg-config nettle-dev

    - name: Format
      run: cargo fmt --check
    - name: Check
      run: cargo check
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::unwrap_used

    - name: Test
      run: cargo test
      env:
        DB_USER: postgres
        DB_PASSWORD: eggs
