name: ci

on:
  push:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Format
        run: cargo fmt --check
      - name: Check
        run: cargo check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::unwrap_used -D clippy::expect_used
      - name: Test
        run: cargo test -- --nocapture
        env:
          RUST_LOG: info,sqlx=error,sea_orm=error
