name: codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:

  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Maximize build space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /opt/hostedtoolcache/go
          sudo rm -rf /opt/hostedtoolcache/node
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/share/powershell
          sudo docker image prune --all --force
          sudo rm -Rf ${JAVA_HOME_8_X64}
          sudo rm -Rf ${JAVA_HOME_11_X64}
          sudo rm -Rf ${JAVA_HOME_17_X64}
          sudo rm -Rf ${RUBY_PATH}
          sudo apt purge -y \
            firefox \
            google-chrome-stable \
            microsoft-edge-stable
          df -h

      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          key: tarpaulin

      - name: Cache Theseus Postgresql Installation
        uses: actions/cache@v4
        with:
          path: ~/.theseus/postgresql
          key: ${{ runner.os }}-theseus-postgresql-${{ hashFiles('**/Cargo.lock') }}

      - name: Start minio
        run: |
          docker compose -f etc/deploy/compose/compose-minio.yaml up -d --wait

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Install llvm-tools-preview
        run: |
          rustup component add llvm-tools-preview

      - name: Test
        # use only one job, trying to reduce memory usage
        run: cargo llvm-cov --codecov --jobs 1 --features _test-s3 --output-path codecov.json
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" # for embedded postgresql

      - uses: codecov/codecov-action@v5
        if: github.repository_owner == 'trustification'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: trustification/trustify
