name: openapi

on:
  push:
    branches:
      - main
      - release/**
    paths:
      - openapi.yaml

jobs:
  trustify-ui:
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'trustification' }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: trustify
      - name: Checkout trustify-ui
        uses: actions/checkout@v4
        with:
          repository: trustification/trustify-ui
          path: trustify-ui
          ref: ${{ github.ref_name }}
      - name: Update trustify-ui
        run: |
          rm ./trustify-ui/client/openapi/trustd.yaml
          cp ./trustify/openapi.yaml ./trustify-ui/client/openapi/trustd.yaml
          cd ./trustify-ui
          git diff
      - name: Create Pull Request - trustify-ui
        uses: trustification/release-tools/.github/actions/create-pr@main
        with:
          path: ./trustify-ui
          commit-message: "update client/openapi/trustd.yaml"
          title: ":seedling: [${{ github.ref_name }}] update client/openapi/trustd.yaml"
          body: |
            The openapi.yaml of trustify has changed
        env:
          TRUSTIFICATION_BOT_ID: ${{ vars.TRUSTIFICATION_BOT_ID }}
          TRUSTIFICATION_BOT_KEY: ${{ secrets.TRUSTIFICATION_BOT_KEY }}
