on:
  discussion:
    types:
      - created

env:
  USERNAME: "@trustification-bot:matrix.org"
  PASSWORD: ${{ secrets.MATRIX_BOT_PASSWORD }}
  ROOM: "#trustification:matrix.org"

jobs:
  notify_channel:
    runs-on: ubuntu-24.04
    steps:
      - name: Send message
        run: |
          podman run --rm docker.io/matrixcommander/matrix-commander:latest --login password --homeserver https://matrix.org --device github --user-login "$USERNAME" --password "$PASSWORD" --room-default "$ROOM" --message "New discussion created: ${{ github.event.discussion.html_url }}"  --logout me
