name: Rust

on:
  push:
    branches:
      - main
      - release/**
  merge_group:
    types:
      - checks_requested
  pull_request:
    branches:
      - main
      - release/**

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Cache Theseus Postgresql Installation
        uses: actions/cache@v4
        with:
          path: ~/.theseus/postgresql
          key: ${{ runner.os }}-theseus-postgresql-${{ hashFiles('**/Cargo.lock') }}

      - name: Format
        run: cargo fmt --check
      - name: Build
        run: cargo check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::unwrap_used -D clippy::expect_used

      - name: Test
        run: cargo test --all-features -- --nocapture
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" # for embedded postgresql
          RUST_LOG: warn,sqlx=error,sea_orm=error
          RUST_MIN_STACK: 50000000 # 50 MB
      - name: Export and Validate Generated Openapi Spec
        run: |
          cargo xtask openapi
          if ! git diff --quiet; then
              echo "::error::Uncommitted changes (run 'cargo xtask openapi' after making api changes)"
              exit 1
          fi
      - name: Ensure schemas are up-to-date
        run: |
          cargo xtask generate-schemas
          if ! git diff --quiet; then
              echo "::error::Uncommitted changes (run 'cargo xtask generate-schemas' after making changes to the models)"
              exit 1
          fi
      - name: Check the docs
        run: |
          cd docs/book
          npm ci
          make all
